# Generated by Django 2.1.2 on 2018-12-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('size', models.IntegerField()),
                ('resolution', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('compress_resolution', models.CharField(max_length=255)),
                ('compress_path', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
