# Generated by Django 2.1.2 on 2018-12-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='compress_size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
