# Generated by Django 2.1.2 on 2018-12-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_upload', '0002_uploadimage_compress_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='compress_size',
            field=models.IntegerField(null=True),
        ),
    ]
