# Generated by Django 2.1.2 on 2018-12-01 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255, verbose_name='HeadLine')),
                ('text', models.TextField(null=True, verbose_name='Text')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('date_time', models.TimeField(auto_now_add=True, verbose_name='Time')),
                ('share', models.BooleanField(verbose_name='Share(NO/YES?)')),
                ('identification_id', models.CharField(default=None, max_length=255)),
            ],
            options={
                'verbose_name': '日记分享管理',
                'verbose_name_plural': '日记分享管理',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_id', models.CharField(max_length=255)),
                ('header', models.CharField(max_length=255)),
                ('text', models.TextField(null=True)),
                ('audio', models.FilePathField(max_length=255, null=True)),
                ('images', models.ImageField(null=True, upload_to='images/')),
                ('code', models.CharField(max_length=255, null=True)),
                ('sort', models.CharField(max_length=255, null=True)),
                ('label', models.CharField(max_length=255, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('date_time', models.TimeField(auto_now=True)),
                ('order_num', models.IntegerField()),
            ],
            options={
                'verbose_name': '日记管理',
                'verbose_name_plural': '日记管理',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(auto_created=True)),
                ('ip', models.GenericIPAddressField(auto_created=True)),
                ('date', models.DateField(auto_now=True)),
                ('date_time', models.TimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('number', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='学号')),
                ('name', models.CharField(max_length=255, verbose_name='姓名')),
                ('room', models.CharField(max_length=255, verbose_name='班级')),
                ('politic_statue', models.CharField(max_length=255, verbose_name='政治面貌')),
                ('gpa_three', models.CharField(max_length=255, verbose_name='学年平均学分绩点')),
                ('sum_scores', models.CharField(max_length=255, verbose_name='学年所获学分总数（除素拓分外）')),
                ('volunteer', models.CharField(max_length=255, verbose_name='志愿服务小时数')),
                ('behavoir_scores', models.CharField(max_length=255, verbose_name='行为规范考核成绩')),
                ('eng_scores', models.CharField(max_length=255, verbose_name='英语成绩')),
                ('phy_scores', models.CharField(max_length=255, verbose_name='体育成绩')),
                ('apply_type', models.CharField(max_length=255, verbose_name='申报项目类型')),
                ('apply_grant_type', models.CharField(max_length=255, verbose_name='申请奖助项目类别')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='用户名')),
                ('icon', models.ImageField(max_length=255, upload_to='', verbose_name='头像地址')),
            ],
        ),
        migrations.AddField(
            model_name='diary',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_diary.User'),
        ),
    ]
